### ISSUE TITLE
Fix a background color of inputs when autofilled

### ISSUE THREAD

**Issue by vepor** [kiwicom/orbit-components#902]
![bug_input_onepassword](https://user-images.githubusercontent.com/7254437/54034293-ce269880-41b6-11e9-8d17-b9ddbeea0f8e.png)

## Expected Behavior
It should stay the same background as of how it's with normal values (= white).

## Current Behavior
The background is blue.

## Possible Solution
The proposed solution from Tales: 
```
div input[data-com-onepassword-filled="light"] { background-color: initial !important; }
```

## Context (Environment)
Environment: Mac, Chrome version 71.0.3578.98 (Official Build) (64-bit)

**Comment by vepor** [comment]
Fixed by #957

**Comment by acqsk** [comment]
I think, changing color is not a good idea in case of inputs with floating labels... ...and I don§t know, hot to override the background and make it transparent...

// Not works...
div input[data-com-onepassword-filled="light"] { background-color: initial !important; }

// Stronger definitions also not works...
body {
  input.k-textbox[data-com-onepassword-filled="light"], select.k-textbox[data-com-onepassword-filled="light"] {
    background: transparent!important;
  }
}

![image](https://user-images.githubusercontent.com/53380201/122017963-b9d49b80-cdc2-11eb-9db7-dfee9c06cb55.png)

![image](https://user-images.githubusercontent.com/53380201/122017988-bf31e600-cdc2-11eb-95a1-ca5ab955ec2f.png)

**Comment by rafaelfaria** [comment]
Any updates on this? I am having the same issues, without a way to override the ones 1password uses (i wish this was optional)

**Comment by LeonBatch** [comment]
If anyones still having this issue, the solution i used was:

`  div input {
    -webkit-box-shadow: 0 0 0px 1000px var(--secondary) inset;
  }`

**Comment by schorfES** [comment]
The `box-shadow` works quite well, but I don't want to explicitly declare a color here. It should be inherited from a parent component, which makes this harder. Instead, I am using a [`background-clip: text`](https://caniuse.com/background-clip-text) approach:

```css
input[data-com-onepassword-filled] {
  background-clip: text;
}
```

**Comment by wendtcode** [comment]
For all the TailwindCSS users out there: `data-[com-onepassword-filled]:bg-clip-text`

**Comment by zackpyle** [comment]
@schorfES I was still getting it when I clicked into the field again. I had to go a little further:

```
body input[data-com-onepassword-filled],
body input[data-com-onepassword-filled]:focus{
  background-clip: text !important;
}
```

I also had to add `!important` AND another selector (`body`). But in the end it worked...

**Comment by frank-laemmer** [comment]
Sorry to bother, I have a couple of related questions:

## How to apply 1PW dark mode?

I see that 1PW now exports `data-com-onepassword-filled="light"`. It also supports `data-com-onepassword-filled="dark"`. But the dark key is not added when I switch my OS to prefers-color-scheme dark. How to make 1PW apply dark to data-com-onepassword-filled in the first place?

## Why not support `:autofill`?

There is a standard HTML attribute to style autofilled elements. Why does 1PW tries to overwrite that with a custom data attribute? I don't want to target any password manager with specific CSS.

https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill


## Tailwind implementation

This is untested. To support dark mode one would need to apply something like this:

```
data-[com-onepassword-filled=light]:bg-indigo-100
data-[com-onepassword-filled=dark]:bg-indigo-900
```

Like noted, I'd rather be able to use:

```
autofill:bg-indigo-100 
dark:autofill:bg-indigo-900
```
